# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtdesigner-workspace/quadcopter-visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(944, 897)
        main_window.setAutoFillBackground(False)
        self.main_widget = QtWidgets.QWidget(main_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_widget.sizePolicy().hasHeightForWidth())
        self.main_widget.setSizePolicy(sizePolicy)
        self.main_widget.setObjectName("main_widget")
        self.main_layout = QtWidgets.QGridLayout(self.main_widget)
        self.main_layout.setContentsMargins(5, 5, 5, 5)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.data_frame = QtWidgets.QFrame(self.main_widget)
        self.data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_frame.setObjectName("data_frame")
        self.data_layout = QtWidgets.QGridLayout(self.data_frame)
        self.data_layout.setContentsMargins(5, 5, 5, 5)
        self.data_layout.setSpacing(0)
        self.data_layout.setObjectName("data_layout")
        self.label_2 = QtWidgets.QLabel(self.data_frame)
        self.label_2.setObjectName("label_2")
        self.data_layout.addWidget(self.label_2, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.data_frame)
        self.graphicsView.setObjectName("graphicsView")
        self.data_layout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.main_layout.addWidget(self.data_frame, 0, 1, 1, 1)
        self.terminal_frame = QtWidgets.QFrame(self.main_widget)
        self.terminal_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.terminal_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.terminal_frame.setObjectName("terminal_frame")
        self.terminal_layout = QtWidgets.QGridLayout(self.terminal_frame)
        self.terminal_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.terminal_layout.setContentsMargins(5, 5, 5, 5)
        self.terminal_layout.setSpacing(0)
        self.terminal_layout.setObjectName("terminal_layout")
        self.label = QtWidgets.QLabel(self.terminal_frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.terminal_layout.addWidget(self.label, 0, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.terminal_frame)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.terminal_layout.addWidget(self.verticalScrollBar, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.terminal_frame)
        self.textBrowser.setObjectName("textBrowser")
        self.terminal_layout.addWidget(self.textBrowser, 1, 1, 1, 1)
        self.main_layout.addWidget(self.terminal_frame, 0, 0, 1, 1)
        self.instrument_frame = QtWidgets.QFrame(self.main_widget)
        self.instrument_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instrument_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instrument_frame.setObjectName("instrument_frame")
        self.instrument_layout = QtWidgets.QGridLayout(self.instrument_frame)
        self.instrument_layout.setContentsMargins(5, 5, 5, 5)
        self.instrument_layout.setSpacing(0)
        self.instrument_layout.setObjectName("instrument_layout")
        self.label_3 = QtWidgets.QLabel(self.instrument_frame)
        self.label_3.setObjectName("label_3")
        self.instrument_layout.addWidget(self.label_3, 0, 1, 1, 1)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.instrument_frame)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.instrument_layout.addWidget(self.verticalScrollBar_2, 1, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.instrument_frame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.instrument_layout.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.main_layout.addWidget(self.instrument_frame, 1, 0, 1, 1)
        self.error_frame = QtWidgets.QFrame(self.main_widget)
        self.error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.error_frame.setObjectName("error_frame")
        self.error_layout = QtWidgets.QGridLayout(self.error_frame)
        self.error_layout.setContentsMargins(5, 5, 5, 5)
        self.error_layout.setSpacing(0)
        self.error_layout.setObjectName("error_layout")
        self.label_4 = QtWidgets.QLabel(self.error_frame)
        self.label_4.setObjectName("label_4")
        self.error_layout.addWidget(self.label_4, 0, 0, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.error_frame)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.error_layout.addWidget(self.graphicsView_2, 1, 0, 1, 1)
        self.main_layout.addWidget(self.error_frame, 1, 1, 1, 1)
        self.main_layout.setColumnStretch(0, 2)
        self.main_layout.setColumnStretch(1, 3)
        self.main_layout.setRowStretch(0, 3)
        self.main_layout.setRowStretch(1, 2)
        main_window.setCentralWidget(self.main_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 944, 22))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_serial_port = QtWidgets.QMenu(self.menu_bar)
        self.menu_serial_port.setObjectName("menu_serial_port")
        main_window.setMenuBar(self.menu_bar)
        self.actionACM0 = QtWidgets.QAction(main_window)
        self.actionACM0.setCheckable(True)
        self.actionACM0.setAutoRepeat(False)
        self.actionACM0.setObjectName("actionACM0")
        self.menu_serial_port.addAction(self.actionACM0)
        self.menu_bar.addAction(self.menu_serial_port.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Quadcopter Visualizer"))
        self.label_2.setText(_translate("main_window", "instruments"))
        self.label.setText(_translate("main_window", "Terminal"))
        self.label_3.setText(_translate("main_window", "Errors"))
        self.label_4.setText(_translate("main_window", "Data"))
        self.menu_serial_port.setTitle(_translate("main_window", "Serial Port"))
        self.actionACM0.setText(_translate("main_window", "ACM0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
